apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox
      role: server
  template:
    metadata:
      labels:
        app: netbox
        role: server
    spec:
      containers:
        - name: server
          image: docker.io/netboxcommunity/netbox
          envFrom:
            - configMapRef:
                name: netbox-env
            - secretRef:
                name: netbox-secret-key
          volumeMounts:
            - mountPath: /media
              name: media
            - mountPath: /opt/netbox/netbox/reports
              name: reports
            - mountPath: /opt/netbox/netbox/scripts
              name: scripts
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http
              path: /api/status/
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: netbox-media
        - name: reports
          persistentVolumeClaim:
            claimName: netbox-reports
        - name: scripts
          persistentVolumeClaim:
            claimName: netbox-scripts
