name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=docker depName=docker.io/netboxcommunity/netbox
      NETBOX_VERSION: v3.7.6
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          files: |
            .github/workflows/build.yaml
            docker/*
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          images: ghcr.io/ffddorf/netbox-kubernetes
          tags: |
            type=raw,value=${{ env.NETBOX_VERSION }},enable={{is_default_branch}}
            type=sha,prefix=${{ env.NETBOX_VERSION }}-,format=short
      - name: Login to GHCR
        uses: docker/login-action@v3
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          context: "{{defaultContext}}:docker"
          build-args: NETBOX_VERSION=${{ env.NETBOX_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
