name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=docker depName=docker.io/netboxcommunity/netbox
      NETBOX_VERSION: v4.4.10
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          since_last_remote_commit: true
          files: |
            .github/workflows/build.yaml
            docker/*
      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          images: ghcr.io/ffddorf/netbox-kubernetes
          tags: |
            type=raw,value=${{ env.NETBOX_VERSION }},enable={{is_default_branch}}
            type=sha,prefix=${{ env.NETBOX_VERSION }}-,format=short
      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          context: "{{defaultContext}}:docker"
          build-args: NETBOX_VERSION=${{ env.NETBOX_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
