name: Build

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      NETBOX_VERSION: v3.7.1
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ffddorf/netbox-kubernetes
          tags: |
            type=raw,value=${{ env.NETBOX_VERSION }},enable={{is_default_branch}}
            type=sha,prefix=${{ env.NETBOX_VERSION }}-,format=short
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker"
          build-args: NETBOX_VERSION=${{ env.NETBOX_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
